#' ApplyWB_to_data -- generate bootstrapped data
#' 
#' This function will generate a wild bootstrap for a single vertex/voxel.
#' The function can be called in parallel to operate on a map. Such usage can be found in the main function
#  or in ComputeMM_WB.R. See below for examples.
#' @param fit_val Fitted values generated by ComputeFits(geeglm_obj)
#' @param resid_val Residual values generated by ComputeResiduals(geeglm_obj)
#' @param sample_val Sample values generated by ComputeMM_WB, or generated by the user
#' @keywords wild bootstrap
#' @export
#' @examples 
#' WB_value <- ApplyWB_to_data(fit_val,resid_val,sample_val)
ApplyWB_to_data <- function(fit_val,resid_val,sample_val) {
  WB_val <- fit_val + resid_val*sample_val
}